name: Full Stack CI + SonarQube

permissions:
  contents: read
  checks: write

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis.

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: maven

      - name: Build and run backend tests
        working-directory: back
        run: mvn clean verify

      - name: Upload Java coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: java-coverage-report
          path: back/target/site/jacoco

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: front/package-lock.json

      - name: Install frontend dependencies
        working-directory: front
        run: npm ci

      - name: Run frontend tests with coverage
        working-directory: front
        run: npm run test -- --browsers=ChromeHeadless --watch=false --code-coverage --karma-config=karma.conf.js

      - name: Upload Node.js coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: node-coverage-report
          path: front/coverage/

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Add summary to Actions tab
        if: always()
        run: |
          echo "### ðŸ“Š Pour visualiser la couverture : tÃ©lÃ©chargez le ZIP des artefacts et ouvrez le fichier index.html dans votre navigateur." >> $GITHUB_STEP_SUMMARY
